/**
 * Typed Cloudflare bindings access.
 *
 * `Cloudflare.Env` is generated by `npm run cf-typegen` from `wrangler.jsonc`,
 * so binding additions automatically flow into these helpers. No more
 * `as Record<string, unknown>` casts.
 *
 * Secrets (ADMIN_PASSWORD) are not in wrangler.jsonc — they're set via
 * `wrangler secret put`. We declare them here via interface merging so
 * `Cloudflare.Env` types also include them.
 */
import { env } from "cloudflare:workers";

declare global {
  namespace Cloudflare {
    interface Env {
      ADMIN_PASSWORD?: string;
    }
  }
}

export function getEnv(): Cloudflare.Env {
  return env;
}

export function getDB(): D1Database {
  if (!env.DB) {
    throw new Error("D1 binding 'DB' is not available in this environment");
  }
  return env.DB;
}

export function getKV(): KVNamespace {
  if (!env.CONTACT_SUBMISSIONS) {
    throw new Error("KV binding 'CONTACT_SUBMISSIONS' is not available in this environment");
  }
  return env.CONTACT_SUBMISSIONS;
}
